apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHB6YmdodXl5
  CLOUDINARY_KEY: MjY0OTU4Nzk0MjUzMTgy
  CLOUDINARY_SECRET: WUJGTWhEQzVLdmZGSTdJMjQ5WmlkX1lfM1RF
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMmhoYVd0dGRYTjBZV1poTnpnaUxDSmhJam9pWTIxaGN6TXpiV1kyTUdnNWFESnJjMkUwZFdoamJqQnlaU0o5LlJZMjNvWmRvYmtQMk1NRTZDeVZxQ0E=
  DB_URL: bW9uZ29kYitzcnY6Ly9hd3NhbmRkZXZvcHMxNF9kYl91c2VyOm1vWGxGeWdLYXBnTE9ua1VAY2x1c3RlcjAuZnBsdGlzOC5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
  SECRET: bXVzdGFmYQ==
