apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHpuanRxcG1t
  CLOUDINARY_KEY: MTIzMzc5MTYxMzEzNDIy
  CLOUDINARY_SECRET: OTlaU0p0akJBbVhuN2NQUGRsX0pjTmhwbHhJ
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMmhoYVd0dGRYTjBZV1poTnpnaUxDSmhJam9pWTIxaGN6TXpiV1kyTUdnNWFESnJjMkUwZFdoamJqQnlaU0o5LlJZMjNvWmRvYmtQMk1NRTZDeVZxQ0E=
  DB_URL: bW9uZ29kYitzcnY6Ly9hd3NhbmRkZXZvcHMyOV9kYl91c2VyOkhqZ09WQ1JIU0NobFRpRUdAY2x1c3RlcjAudmRzYnJ3dC5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
  SECRET: bXVzdGFmYQ==
